// examples/solid-query/src/index.tsx

import { QueryClientProvider } from '@tanstack/solid-query';
import { queryClient } from './query';
import { App } from './App';
import { render } from 'solid-js/web';
import { SolidQueryDevtools } from '@tanstack/solid-query-devtools';
import './style.css';

render(
    () => (
        <QueryClientProvider client={queryClient}>
            <App />
            <SolidQueryDevtools />
        </QueryClientProvider>
    ),
    document.querySelector('#root')!
);

// examples/react-query/src/index.tsx

import { QueryClientProvider } from '@tanstack/react-query';
import React from 'react';
import ReactDOM from 'react-dom/client';
import { queryClient } from './query';
import { App } from './App';

ReactDOM.createRoot(document.querySelector('#root')!).render(
    <React.StrictMode>
        <QueryClientProvider client={queryClient}>
            <App />
        </QueryClientProvider>
    </React.StrictMode>
);
